### ISSUE TITLE
Feature Request: Enable fetching Leaderboard information by its unique `Slug`

### ISSUE THREAD

**Issue by erunks** [leaderboardsgg/leaderboard-backend#136]
I would like to propose that we add an API route to fetch the information for a given leaderboard by its unique `slug`. This will help the front end application more easily be able to request the correct data. 

See https://github.com/leaderboardsgg/leaderboard-site/issues/545 as to how it would be used

### Affected Functionality
Nothing should be effected by this change

### Other Relevant Issues
https://github.com/leaderboardsgg/leaderboard-site/issues/545

**Comment by Dalet** [comment]
So currently we can only get by id `GET /api/leaderboards/:id`, or get literally everything with `GET /api/leaderboards`.

I suggest adding a `slug` filter like this: `GET /api/leaderboard?slug={slug}`.  Since the slug is unique it will always return a list with zero or one element.

**Comment by Dalet** [comment]
We should talk about the design. (in response to this comment on my PR https://github.com/leaderboardsgg/leaderboard-backend/pull/140#discussion_r1176861305)

I've been hesitant about this. Let's review the options:

### 1. "get leaderboards" endpoint with slug filter `GET /leaderboards/?slug=:slug`
I thought that since slugs may change, it makes sense to make a "query" for it. Even if it will always return either one or zero results.
A future problem with `/leaderboards?slug` could be that later on, we might decide to not include all leaderboard properties in the list items to reduce bandwidth usage. This will require an additional request to GET /api/leaderboards/:id to get the missing details.

### 2. "get by id or slug" endpoint `GET /leaderboards/:idOrSlug`
If we reuse the same endpoint to get by id and to get by slug (GET /leaderboards/:idOrSlug), then slugs with the same format as ids should be forbidden to prevent ambiguity, but wouldn't that be kinda lame? (thinking of the game named [140](https://store.steampowered.com/app/242820/140/), *which happens to be the id of my PR lol*)

### 3. "get by slug" endpoint `GET /leaderboards/slug/:slug`
A dedicated endpoint to retrieve by slug. I changed my mind and I actually prefer this now.
I'm not sure if this is purely RESTful but it seems like the most practical one.

**Comment by zysim** [comment]
As done in #140, we've gone with option 2.
